export const INITIA_ACCOUNT_ABI = {
  address: '0x1',
  name: 'account',
  friends: ['0x1::table', '0x1::object'],
  exposed_functions: [
    {
      name: 'account_info',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['address'],
      return: ['bool', 'u64', 'u64', 'u8', 'bool'],
    },
    {
      name: 'create_account',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['address'],
      return: ['u64'],
    },
    {
      name: 'create_account_script',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['address'],
      return: [],
    },
    {
      name: 'create_address',
      visibility: 'friend',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['vector<u8>'],
      return: ['address'],
    },
    {
      name: 'create_object_account',
      visibility: 'friend',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['address'],
      return: ['u64'],
    },
    {
      name: 'create_signer',
      visibility: 'friend',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['address'],
      return: ['signer'],
    },
    {
      name: 'create_table_account',
      visibility: 'friend',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['address'],
      return: ['u64'],
    },
    {
      name: 'exists_at',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'get_account_info',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool', '0x1::account::AccountInfo'],
    },
    {
      name: 'get_account_number',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['u64'],
    },
    {
      name: 'get_account_number_with_info',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['&0x1::account::AccountInfo'],
      return: ['u64'],
    },
    {
      name: 'get_sequence_number',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['u64'],
    },
    {
      name: 'get_sequence_number_with_info',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['&0x1::account::AccountInfo'],
      return: ['u64'],
    },
    {
      name: 'is_base_account',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'is_base_account_with_info',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['&0x1::account::AccountInfo'],
      return: ['bool'],
    },
    {
      name: 'is_blocked',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'is_blocked_with_info',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['&0x1::account::AccountInfo'],
      return: ['bool'],
    },
    {
      name: 'is_module_account',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'is_module_account_with_info',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['&0x1::account::AccountInfo'],
      return: ['bool'],
    },
    {
      name: 'is_object_account',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'is_object_account_with_info',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['&0x1::account::AccountInfo'],
      return: ['bool'],
    },
    {
      name: 'is_table_account',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'is_table_account_with_info',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['&0x1::account::AccountInfo'],
      return: ['bool'],
    },
  ],
  structs: [
    {
      name: 'AccountInfo',
      is_native: false,
      abilities: ['copy', 'drop'],
      generic_type_params: [],
      fields: [
        { name: 'account_number', type: 'u64' },
        { name: 'sequence_number', type: 'u64' },
        { name: 'account_type', type: 'u8' },
        { name: 'is_blocked', type: 'bool' },
      ],
    },
  ],
} as const;
